---
# Source: showks-aggregator/templates/rolebinding.yml
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: showks-aggregator-access
  namespace: showks
rules:
- apiGroups: ["","apps","extensions"]
  resources: ["services","deployments","ingresses"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: showks-aggregator-access-binding
  namespace: showks
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: showks-aggregator-access
  apiGroup: rbac.authorization.k8s.io

---
# Source: showks-aggregator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-aggregator-temp
  namespace: showks
  labels:
    app: showks-aggregator-temp
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: app-port
  selector:
    app: showks-aggregator-temp

---
# Source: showks-aggregator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-aggregator-temp
  namespace: showks
  labels:
    app: showks-aggregator-temp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-aggregator-temp
  template:
    metadata:
      labels:
        app: showks-aggregator-temp
    spec:
      containers:
        - name: showks-aggregator-temp
          image: gcr.io/ipc-containerdays/showks-aggregator:stg-485e7d97b135e64441eac01d0255571c64315f99
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: showks-config
                  key: domain
            - name: ALLOW_HOST
              value: https://portal$(DOMAIN)
          ports:
            - name: app-port
              containerPort: 8081
              protocol: TCP

