---
# Source: showks-portal-frontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-portal-frontend-temp
  namespace: showks
  labels:
    app: showks-portal-frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: app-port
  selector:
    app: showks-portal-frontend

---
# Source: showks-portal-frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-portal-frontend-temp
  namespace: showks
  labels:
    app: showks-portal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-portal-frontend
  template:
    metadata:
      labels:
        app: showks-portal-frontend
    spec:
      containers:
        - name: showks-portal-frontend
          image: gcr.io/ipc-containerdays/showks-portal-frontend:stg-bfa24a258a1b1bcae1571a3fdc502939c898550f
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: showks-config
                  key: domain
            - name: AGGREGATOR_URL
              value: http://aggregator$(DOMAIN)
          ports:
            - name: app-port
              containerPort: 3000
              protocol: TCP

